name: Build Tweak
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          path: theos
      - name: Build
        run: |
          export THEOS=$PWD/theos
          make package
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: NewLOL
          path: packages/*.deb
